(defun color-theme-cbrecabarren ()
  (interactive)
  (color-theme-install
   '(color-theme-cbrecabarren
     ((background-color . "#121212")
      (background-mode . dark)
      (cursor-color . "#00FF00")
      (foreground-color . "#E6E1DC"))
     (default ((t nil)))
     (bold ((t (:bold t))))
     (bold-italic ((t (:italic t :bold t))))
     (fringe ((t (:background "#030303"))))
     (font-lock-builtin-face ((t (:foreground "#D0D0FF"))))
     (font-lock-comment-face ((t (:foreground "#BC9458" :italic t))))
     (font-lock-constant-face ((t (:foreground "#6D9CBE"))))
     (font-lock-doc-string-face ((t (:foreground "#A5C261"))))
     (font-lock-function-name-face ((t (:foreground "#FFC66D"))))
     (font-lock-keyword-face ((t (:foreground "#CC7833"))))
     (font-lock-preprocessor-face ((t (:foreground "#CC7833"))))
     (font-lock-reference-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-string-face ((t (:foreground "#A5C261"))))
     (font-lock-type-face ((t (:foreground "white"))))
     (font-lock-variable-name-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-warning-face ((t (:foreground "pink"))))
     (paren-face-match-light ((t (:foreground "#FFC66D" :background "#555577"))))
     (highlight ((t (:background "#333333"))))
     (italic ((t (:italic t))))
     (modeline ((t (:background "black" :foreground "white" :height 0.8))))
     (modeline-buffer-id ((t (:background "black" :foreground "white"))))
     (modeline-mousable ((t (:background "black" :foreground  "white"))))
     (modeline-mousable-minor-mode ((t (:background "black" :foreground "white"))))
     (region ((t (:background "#27408b"))))
     (primary-selection ((t (:background "#27408b"))))
     (isearch ((t (:background "#03109b"))))
     (lazy-highlight ((t (:background "#333333"))))
     (zmacs-region ((t (:background "#27408b"))))
     (cua-rectangle ((t (:background "#27408b"))))
     (secondary-selection ((t (:background "DarkSlateBlue")))) 
     (flymake-errline ((t (:background "LightSalmon" :foreground 
                                       "black")))) 
     (flymake-warnline ((t (:background "LightSteelBlue" :foreground 
                                        "black"))))
     (underline ((t (:underline t)))) 
     (minibuffer-prompt ((t (:bold t :foreground "#4470FF"))))
     (linum ((t (:background "#050505" :foreground "#EEEEEE" :height 0.8))))
     (show-paren-match-face ((t (:background "#FFFF00" :foreground "#000000" :bold t))))
     (ido-only-match ((t (:foreground "#FFD700"))))
     (ido-subdir ((t (:foreground "#7CFC00"))))
     (link-face ((t (:foreground "#0033FF" :underline t))))
     (erb-face ((t (:background "#222222"))))
     (link-visited ((t (:foreground "#0088BB"))))
    ))
)
